# Generated by Django 5.2.6 on 2025-09-26 14:22

import notes.models.niveau
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name': 'Élève', 'verbose_name_plural': 'Élèves'},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'verbose_name': 'Enseignant', 'verbose_name_plural': 'Enseignants'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AlterField(
            model_name='niveau',
            name='nom',
            field=models.CharField(max_length=2, unique=True, validators=[notes.models.niveau.nom_vide]),
        ),
    ]
